# SPDX-FileCopyrightText: 2022 nerdyscout <https://github.com/nerdyscout/>
#
# SPDX-License-Identifier: CC0-1.0

name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: KiBot
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: KiBot
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: PlatformIO
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: PlatformIO
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
